contentTypeName = "posts"
themeColor = "orange"
showMenuItems = 2
showLanguageSelector = true
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = true
readingTime = true
Toc = true

[twitter]
creator = "chuxubank"
site = ""
