[[main]]
identifier = "about"
name = "About"
url = "/en/about"
weight = "10"

[[main]]
identifier = "showcase"
name = "Showcase"
url = "/en/showcase"
weight = "20"

[[main]]
identifier = "search"
name = "Search (^K)"
url = ""
weight = "30"
