TocTitle = "Table of Contents"
copyright = "chuxubank"
keywords = ""
menuMore = "Show more"
minuteReadingTime = "min read"
missingBackButtonLabel = "Back to home page"
missingContentMessage = "Page not found..."
newerPosts = "Newer posts"
olderPosts = "Older posts"
owner = "X.Chuu"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "Listen to bothsides and you will be enlightened; heed only one side and you will be benighted."
updatedDatePrefix = "Updated"
words = "words"

[logo]
logoText = "InitSeq"
logoHomeLink = "/en"
