copyright = "旭"
keywords = ""
menuMore = "更多"
minuteReadingTime = "分钟"
missingBackButtonLabel = "回家"
missingContentMessage = "无序之处..."
newerPosts = "新"
olderPosts = "旧"
owner = "旭"
readMore = "阅读更多"
readOtherPosts = "阅读其他"
subtitle = "兼听则明，偏信则暗"
updatedDatePrefix = "更新于"
words = "字"

[logo]
logoText = "初序"
logoHomeLink = "/"
