Toc = true
autoCover = true
centerTheme = true
contentTypeName = "posts"
fullWidthTheme = false
readingTime = true
showLanguageSelector = true
showLastUpdated = true
showMenuItems = 3
themeColor = "orange"

[twitter]
creator = "chuxubank"
site = ""
