name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: |
        npm i -g hexo-cli
        npm i
    - name: Setup Git
      run: |
        git config --global user.email "chuxubank@qq.com"
        git config --global user.name "chuxubank"
    - name: Hexo Generate
      run: |
        cp source/_data/icarus.yml themes/icarus/_config.yml
        hexo g
    - name: Hexo Deploy
      run: hexo d
      if: success()