name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
        submodules: true
    
    - uses: actions/setup-node@v1
    
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: yarn
    
    - name: Setup git
      run: |
        git config --global user.email "chuxubank@qq.com"
        git config --global user.name "Misaka"
    
    - name: Generate
      run: yarn build
    
    - name: Deploy
      run: yarn deploy
      if: success()
