name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: |
        yarn global add hexo-cli
        yarn install
    - name: Hexo Generate
      run: hexo clean && hexo g && hexo d
