name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - uses: actions/setup-node@v1
    
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Install dependencies
      run: yarn
    
    - name: Setup git
      run: |
        git config --global user.email "chuxubank@qq.com"
        git config --global user.name "chuxubank"
    
    - name: Generate
      run: |
        cp source/_data/icarus.yml themes/icarus/_config.yml
        yarn build
    
    - name: Deploy
      run: yarn deploy
      if: success()