name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    - uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: Install Dependencies
      run: |
        npm i -g hexo-cli
        npm i
    - name: Hexo Generate
      run: hexo clean && hexo g && hexo d
