name: CI

on:
  push:
    branches:
      - hexo

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: |
        npm i -g hexo-cli
        npm i
    - name: Hexo Generate
      run: hexo g
    - name: Hexo Deploy
      run: hexo d
      if: success()