name: CI

on:
  push:
    branches:
      - hexo

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: hexo
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: |
        npm i -g hexo-cli
        npm i
    - name: Setup Git
      run: |
        git config --global credential.https://github.com/chuxubank/chuxubank.github.io.git.username chuxubank
        echo ${{ secrets.GITHUB_TOKEN }}
        git config --global user.email "chuxubank@qq.com"
        git config --global user.name "chuxubank"
    - name: Hexo Generate
      run: hexo g
    - name: Hexo Deploy
      run: hexo d
      if: success()